spring:
  cloud:
    stream:
      rabbit:
        default:
          producer:
            transacted: true
            autoBindDlq: true
            republishToDlq: true
          consumer:
            transacted: true
            autoBindDlq: true
            republishToDlq: true
            maxAttempts: 10

      bindings:
        input:
          destination: my-input
          group: my-group
          binder: local_rabbit
        output:
          destination: my-output
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
